### ISSUE TITLE
Add ability to set a threshold for trigger

### ISSUE THREAD

**Issue by toddparker** [filamentgroup/porthole#3]
I think an offset might be cool because you might want to say "kick this in if it's more than 200px in the viewport" so you don't start an animation before it's really in view. A negative value would let you say "kick this in if it's 200px from being in the viewport"

**Comment by scottjehl** [comment]
This is in, but zach and I have discussed improving it by offsetting the calculated viewport top and bottom. Currently the calculated top of the element in question is manipulated, but the bottom stays the same, which helps us make sure the element activates if it's fully in the viewport but not scrolled up.

**Comment by toddparker** [comment]
@scottjehl - we added this, just need to document?

**Comment by scottjehl** [comment]
https://master-origin-porthole.fgview.com/demo/
