### ISSUE TITLE
Elements that come into view due to media queries

### ISSUE THREAD

**Issue by Rubious** [filamentgroup/porthole#6]
If you have an element that comes into view at a certain media query, then resizing the window doesn't re-trigger this to show (even with the latest commit).

**Comment by scottjehl** [comment]
@Rubious you can update the listener manually by triggering a "porthole" event on the window. Does that help satisfy your situation? If not, we can reopen. Thanks.

**Comment by Rubious** [comment]
Hi

The issue is, I have an element that is hidden on desktop using a media query, like this:

```
<div class="hide-on-desktop">
  <img data-scroll-activate src='...'>
</div>
```

When the page loads, even though that image is not visible (it's display:none) it adds the class "inviewport" to the img.

When I resize the window and the image starts displaying, nothing changes - it still has inviewport on it.

I've written my own little script that also detects if the element .is(":visible") using jQuery. Is that the best way to do it, or am I missing something?

Thanks!
